import java.awt.Color;
import java.awt.Dimension;
import java.awt.Panel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JFrame;
import javax.swing.JPanel;

public class Main {

	public static void main(String[] args) {
		new Screen(1280,800);
		//System.out.println("Icon: "+new Entity().autoGeneratedIcon());
	}

}
